name: Deploy Backend

on:
  push:
    branches:
      - main

jobs:
  deploy-backend:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v2

      - name: Setup Node
        uses: actions/setup-node@v2
        with:
          node-version: 18

      - name: Install dependencies
        working-directory: ./Student-ChatBot-Backend
        run: npm install

      - name: Crete .env file
        run: |
          echo "PORT=5001" >> .env
          echo "MONGODB_URI=${{ mongodb+srv://white728:admin@cluster0.6gf9j.mongodb.net/?retryWrites=true&w=majority&appName=Cluster0 }}" >> .env
          echo " GEMINI_API_KEY=${{ secrets.AIzaSyCbr4dG2cqoQsrKksphyZO2vL4sgEOUQFQ }}" >> .env
        working-directory: ./Student-ChatBot-Backend

      - name: Run Backend
        working-directory: ./Student-ChatBot-Backend
        run: npm run start

      - name: Upload production-ready build files
        uses: actions/upload-artifact@v2
        with:
          name: backend